[build]
  base = "frontend/patient-advocacy-frontend"
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5178
  targetPort = 5178
  publish = "dist"
  autoLaunch = true
  framework = "#custom"

# Redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Set up headers for security
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
